[profile.default]
solc = "0.8.23"
src = 'src'
out = 'out'
libs = ['lib']
via_ir = true
optimizer_runs = 1000000
eth-rpc-url = 'http://localhost:8545'

fs_permissions = [
    { access = "read", path = "out" }, 
    { access = "read-write", path = ".forge-snapshots/" }
]

extra_output = ['storageLayout']

[rpc_endpoints]
local = "http://localhost:8545"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Add this section
[profile.default.etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }